import { registerRoute } from 'workbox-routing';
import { precacheAndRoute, precacheController } from 'workbox-precaching';
import { CacheFirst } from 'workbox-strategies';
// manifest import will be autogenerated by webpack
precacheAndRoute(self.__WB_MANIFEST || []);
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    console.log('helodaaa');
  });
}
